spring:
  datasource:
    url: jdbc:mysql://yamanote.proxy.rlwy.net:35127/railway?useSSL=true&allowPublicKeyRetrieval=true&serverTimezone=UTC&socketTimeout=30000&connectTimeout=30000
    username: root
    password: ZRWLsiFhnBgAudASOfeClGdhnCTRbruW
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000
      initialization-fail-timeout: 0
      leak-detection-threshold: 10000

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        connection.provider_disables_autocommit: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always