spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME}?useSSL=true&allowPublicKeyRetrieval=true&serverTimezone=UTC&connectTimeout=5000&socketTimeout=10000
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: ${spring.application.name}-HikariPool
      maximum-pool-size: ${DB_POOL_SIZE:5}
      minimum-idle: ${DB_POOL_MIN_IDLE:1}
      connection-timeout: ${DB_CONN_TIMEOUT:5000}
      initialization-fail-timeout: 0
      max-lifetime: ${DB_CONN_MAX_LIFETIME:300000}
      validation-timeout: 2000
      leak-detection-threshold: ${DB_LEAK_DETECTION_THRESHOLD:60000}

  jpa:
    hibernate:
      ddl-auto: ${DB_HIBERNATE_DDL:update}
    show-sql: ${DB_SHOW_SQL:true}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        connection.provider_disables_autocommit: true
        jdbc:
          time_zone: UTC
        format_sql: true
        generate_statistics: false
      javax:
        persistence:
          validation:
            mode: none

  sql:
    init:
      mode: never

# Configurações adicionais recomendadas
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
      springframework:
        jdbc:
          core: DEBUG
        orm:
          jpa: DEBUG