spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=true&allowPublicKeyRetrieval=true&serverTimezone=UTC&socketTimeout=10000&connectTimeout=10000
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    fallback: ${DATASOURCE_FALLBACK:false}

    hikari:
      pool-name: RailwayHikariPool
      maximum-pool-size: 5  # Reduzido para testes
      minimum-idle: 1
      connection-timeout: 5000  # 5 segundos
      initialization-fail-timeout: 1000  # Falha rápido
      max-lifetime: 300000  # 5 minutos
      validation-timeout: 2000
      leak-detection-threshold: 5000

  jpa:
    hibernate:
      ddl-auto: none  # Desativado temporariamente
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        connection.provider_disables_autocommit: true
        temp.use_jdbc_metadata_defaults: false

management:
  health:
    db:
      enabled: false  # Desativado temporariamente