spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=true&allowPublicKeyRetrieval=true&serverTimezone=UTC&socketTimeout=30000&connectTimeout=30000
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: RailwayHikariPool
      maximum-pool-size: 10
      minimum-idle: 3
      connection-timeout: 30000 # 30 segundos
      initialization-fail-timeout: 0 # Falha imediata
      max-lifetime: 600000 # 10 minutos
      leak-detection-threshold: 10000 # 10 segundos

  jpa:
    hibernate:
      ddl-auto: validate # Valida schema sem alterar estrutura
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        connection.provider_disables_autocommit: true
        order_inserts: true
        order_updates: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    db:
      enabled: true
      query: "SELECT 1" # Query de health check

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.zaxxer.hikari: INFO