spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME}?useSSL=true&allowPublicKeyRetrieval=true&serverTimezone=UTC&connectTimeout=5000&socketTimeout=10000
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: ${spring.application.name}-HikariPool
      maximum-pool-size: 5
      minimum-idle: 1
      connection-timeout: 5000
      initialization-fail-timeout: 0 # Falha imediatamente
      max-lifetime: 300000
      validation-timeout: 2000

  jpa:
    hibernate:
      ddl-auto: none # Desativado temporariamente
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect # Versão não-depreciada
        connection.provider_disables_autocommit: true
        boot:
          allow_jdbc_metadata_access: false # Substitui o setting depreciado

  sql:
    init:
      mode: never # Desativa inicialização automática